///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FoodModel {
/*
{
  "mainText": "Chicken Slab Burger",
  "price": 209,
  "qty": 0,
  "id": 1
}
*/

  String? mainText;
  int? price;
  int qty = 0;
  int? id;

  FoodModel({
    this.mainText,
    this.price,
    required this.qty,
    this.id,
  });
  FoodModel.fromJson(Map<String, dynamic> json) {
    mainText = json['mainText']?.toString();
    price = json['price']?.toInt();
    qty = json['qty'].toInt();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mainText'] = mainText;
    data['price'] = price;
    data['qty'] = qty;
    data['id'] = id;
    return data;
  }
}
